name: Test

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v3
        with:
          repository: 'magodo/aztfy'
          ref: 'auth_config'
      - name: Install aztfy
        run: |
          go install
      - name: Export the demo rg using oidc
        run:
          mkdir /tmp/aztfytest && cd /tmp/aztfytest && $HOME/go/bin/aztfexport rg -n -f -use-oidc-cred --tenant-id=${{ secrets.ARM_TENANT_ID }} -s ${{ secrets.ARM_SUBSCRIPTION_ID}} --client-id ${{ secrets.ARM_CLIENT_ID }} --plain-ui aztfy
      - name: Verify
        run:
          cd /tmp/aztfytest && terraform state list
