name: Test-wif

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - uses: actions/checkout@v3
      - name: Run Terraform
        run: |
          cd wif
          terraform init
          terraform apply -auto-approve -TF_VAR_id_token_request_url="${ACTIONS_ID_TOKEN_REQUEST_URL}" -TF_VAR_id_token_request_token="${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" -TF_VAR_tenant_id=${{ secrets.ARM_TENANT_ID }} -TF_VAR_sub_id=${{ secrets.ARM_SUBSCRIPTION_ID }} -TF_VAR_client_id=${{ secrets.ARM_CLIENT_ID }}
